### PR TITLE
faster version

### PR DESCRIPTION
**Pull request by clararehmann**

### CODE REVIEW

**Comment by andrewkern** [comment]
this looks good to me. @cjbattey do you want to put your eyes on this PR?

**Comment by cjbattey** [comment]
Sorry I'm behind here. @clararehmann can you write up a short description of what's in this PR? If possible, include some example output and comparison with the current plotting script. Before we merge it into the master locator repo we need to run tests on at least a couple different datasets to make sure it's ready for public consumption. We also need to update the readme to document it.

**Comment by cjbattey** [comment]
We also need to edit the setup.py script to install the new dependencies -- I think it's `pyshp`, `shapely`, `scikit-learn`, and `pyproj`.  If you look in locator/setup.py we can just add them to the `install_requires=[...]` list.

**Comment by clararehmann** [comment]
> We also need to edit the setup.py script to install the new dependencies -- I think it's `pyshp`, `shapely`, `scikit-learn`, and `pyproj`. If you look in locator/setup.py we can just add them to the `install_requires=[...]` list.

The map is in .zarr format now so the only new dependency should be scikit-learn - I'll double check that I don't use the others in the script

**Comment by cjbattey** [comment]
ok got it working locally. Really nice work @clararehmann. A couple ideas: 
1. we should plot the training localities underneath the KDE and using a color that isn't part of the KDE color ramp. I think we can just move `ax1.scatter(trainx, trainy, ...)` on top of `sns.kdeplot(xpred, ypred, ...)`.
2. It would be good to have a legend for the color ramp. this stackexchange post seems to have a solution: https://stackoverflow.com/questions/39328551/colorbar-for-seaborn-kdeplot

**Comment by andrewkern** [comment]
one question I have is do we need to provide the zarr files for every user? should we have an option to download? how big is that directory on disk anyway?

**Comment by andrewkern** [comment]
[okay that was 3 questions]

**Pull request closed without merging**
